### ISSUE TITLE
Issue re: SetHealth

### ISSUE THREAD

**Issue by raum266** [BtoBastian/EpicSpleef#10]
arena/SpleefArena.java, 

160			player.setHealth(20D);
161			player.setMaxHealth(20D);

These two lines need to be switched - as well as the instance right above them. You're trying to set the health to something that might not be available due to max health being lower. 

We have several games that will lower max health depending on certain situations - If they do not fully exit said plugins before trying to join Spleef, it will throw an error, as you cannot set health higher than the max.

**Comment by BtoBastian** [comment]
Thank you.
This will be fixed soon. :-)

**Comment by BtoBastian** [comment]
Fixed.
